name: 'S3 Helm release'
description: 'Build and release Helm packages on s3 repositories.'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  version:
    description: Override Helm chart version.
    required: false
  appVersion:
    description: Override Helm chart appVersion.
    required: false
  chart:
    description: The local Helm cart folder path.
    default: './'
    required: true
  repo:
    description: The S3 Helm repository bucket URL.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.chart }}
    - ${{ inputs.repo }}
    - ${{ inputs.forceRelease }}